name: myfridge_test
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ðŸ”¹ Utility & UI
  mobile_scanner: ^4.0.0
  pie_chart: ^5.4.0
  fl_chart: ^0.66.0
  intl: ^0.20.2
  image_picker: ^1.2.0
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.8
  http: ^0.13.6
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^8.0.0
  timezone: ^0.9.2

  # ðŸ”¹ Firebase (à¸Šà¸¸à¸”à¹€à¸ªà¸–à¸µà¸¢à¸£à¸—à¸µà¹ˆà¹€à¸‚à¹‰à¸²à¸à¸±à¸™à¹„à¸”à¹‰à¸—à¸±à¹‰à¸‡à¸«à¸¡à¸”)
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7
  firebase_messaging: ^14.9.4

  # ðŸ”¹ Notifications (Local)
  flutter_local_notifications: ^17.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png
